# Generated by Django 4.0.3 on 2022-03-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_category_category_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_post',
            new_name='CategoryPost',
        ),
    ]
