# Generated by Django 4.0.3 on 2022-03-30 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9bf704f4-43bb-45df-95aa-f69fdf56d569'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f5d09ca-a98f-4964-a70f-7f388ae40fe6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('50614443-41fe-434d-903a-acf7f82100ed'), editable=False, primary_key=True, serialize=False),
        ),
    ]
