# Generated by Django 4.0.3 on 2022-03-30 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_allergen_id_alter_flavour_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('796f0ffa-f756-47a6-b1a9-5afa66a1d89c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65262a88-2aec-45c6-a687-00040009da71'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('d74ee214-e4c7-4ec8-9ced-380f3a74dc5a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
