# Generated by Django 4.0.3 on 2022-03-30 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_allergen_id_alter_flavour_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06d8e46f-4472-423e-bc3d-9f0ab16bd289'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc73b51d-ed4d-44ee-bde5-c709663b7eee'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('3b73bc17-193a-497b-90bc-3538bbff07d2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
