# Generated by Django 4.0.3 on 2022-03-30 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_allergen_id_alter_flavour_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3cae29ef-c35c-4592-a793-46f30ba37bd4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e3b6dc2-ac53-44fd-93f2-64ecde371b14'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('f706b157-da72-47dd-9d2b-a3115495f637'), editable=False, primary_key=True, serialize=False),
        ),
    ]
