# Generated by Django 4.0.3 on 2022-03-30 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_allergen_id_alter_flavour_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17fa4397-ad28-4279-b10e-d65eae8086f2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3927c22c-3e12-423c-b4b3-cb5bb6599885'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('e3cfa17a-07b0-4256-969e-f123f4e81afa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
