# Generated by Django 4.0.3 on 2022-03-30 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_allergen_id_alter_flavour_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('046825a7-8524-45ea-826c-8ca5ba0d975a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f495e3fc-5639-45d6-a02f-4a744a3de7c1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('abfbcc7b-6c88-4bf3-aa10-0c1a299a2e6a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
