# Generated by Django 4.0.3 on 2022-03-30 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_allergen_id_alter_flavour_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('28950ef6-47a9-474c-9689-575652d223f1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('09e5591d-c30e-47e9-998e-c81d248a9aca'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('1098850b-d75f-4622-81cf-80f127d63071'), editable=False, primary_key=True, serialize=False),
        ),
    ]
