# Generated by Django 4.0.3 on 2022-03-30 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_allergen_id_alter_flavour_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f5b7c297-70c2-4b80-95cc-270352a86221'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6dbdfa6c-4f85-47e6-9f94-a4b360e77c92'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0a1e5d6a-e3fa-45f2-98c7-796ef8ed8f35'), editable=False, primary_key=True, serialize=False),
        ),
    ]
