# Generated by Django 4.0.3 on 2022-03-30 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_allergen_id_alter_flavour_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eeba196e-3361-47ca-a916-29ae2d5b0e21'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('443aaca1-21ba-4b89-a522-8cc942958016'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('02b6e437-a017-4edc-be64-7d19cfc93d58'), editable=False, primary_key=True, serialize=False),
        ),
    ]
